"""Object storage interface. Original files live here; PostgreSQL stores metadata, keys, and hashes."""

from typing import BinaryIO, Protocol


class ObjectStore(Protocol):
    def put(self, key: str, data: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...
    def open(self, key: str) -> BinaryIO: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def healthcheck(self) -> None: ...


def content_key(org_id: str, sha256: str, ext: str) -> str:
    """Content-addressed key. No user-supplied path components ever reach storage."""
    safe_ext = "".join(c for c in ext.lower() if c.isalnum())[:8]
    return f"orgs/{org_id}/originals/{sha256[:2]}/{sha256}.{safe_ext or 'bin'}"
