"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 19:18:28.495459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('oidc_subject', name=op.f('uq_users_oidc_subject'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('program_outline', 'review_report', 'webpage_extract', 'course_outline', 'assessment_document', 'pasted_text', 'other', name='documenttype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('course', 'program_outcome', 'course_outcome', 'topic', 'assessment', 'activity', name='entitytype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('stable_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entities_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('organization_id', 'entity_type', 'stable_key', name=op.f('uq_entities_organization_id_entity_type_stable_key'))
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_organization_id'), 'entities', ['organization_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled', name='jobstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('current_stage', sa.String(length=60), nullable=True),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_jobs_idempotency_key'))
    )
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'reviewer', 'viewer', name='role', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_memberships_organization_id_user_id'))
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('route', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('requested_model', sa.String(length=120), nullable=False),
    sa.Column('returned_model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=True),
    sa.Column('cache_key', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_model_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_index(op.f('ix_model_runs_cache_key'), 'model_runs', ['cache_key'], unique=False)
    op.create_index(op.f('ix_model_runs_organization_id'), 'model_runs', ['organization_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=True),
    sa.Column('parent_degree', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_programs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_programs_organization_id_code'))
    )
    op.create_index(op.f('ix_programs_organization_id'), 'programs', ['organization_id'], unique=False)
    op.create_table('curriculum_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('cohort', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='versionstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('published_from_scenario_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_curriculum_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['curriculum_versions.id'], name=op.f('fk_curriculum_versions_parent_version_id_curriculum_versions')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_curriculum_versions_program_id_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_curriculum_versions_published_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_versions')),
    sa.UniqueConstraint('program_id', 'label', name=op.f('uq_curriculum_versions_program_id_label'))
    )
    op.create_index(op.f('ix_curriculum_versions_organization_id'), 'curriculum_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_curriculum_versions_program_id'), 'curriculum_versions', ['program_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('retrieval_date', sa.Date(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('cohort_applicability', sa.String(length=200), nullable=True),
    sa.Column('authority_note', sa.String(length=300), nullable=True),
    sa.Column('processing_status', sa.Enum('uploaded', 'processing', 'processed', 'partial', 'failed', name='processingstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('organization_id', 'sha256', name=op.f('uq_document_versions_organization_id_sha256'))
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_organization_id'), 'document_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_versions_sha256'), 'document_versions', ['sha256'], unique=False)
    op.create_table('entity_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.Enum('extracted', 'manual', 'ai_inferred', 'rule_derived', 'synthetic_fixture', name='origin', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description,''))", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_entity_revisions_created_by_users')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_revisions_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entity_revisions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_revisions')),
    sa.UniqueConstraint('entity_id', 'revision_number', name=op.f('uq_entity_revisions_entity_id_revision_number'))
    )
    op.create_index(op.f('ix_entity_revisions_entity_id'), 'entity_revisions', ['entity_id'], unique=False)
    op.create_index('ix_entity_revisions_fts', 'entity_revisions', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_entity_revisions_organization_id'), 'entity_revisions', ['organization_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('pathways',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_pathways_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_pathways_program_id_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathways')),
    sa.UniqueConstraint('program_id', 'code', name=op.f('uq_pathways_program_id_code'))
    )
    op.create_index(op.f('ix_pathways_organization_id'), 'pathways', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pathways_program_id'), 'pathways', ['program_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_run_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], name=op.f('fk_tool_calls_model_run_id_model_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index(op.f('ix_tool_calls_model_run_id'), 'tool_calls', ['model_run_id'], unique=False)
    op.create_table('activity_revision_details',
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_format', sa.String(length=120), nullable=True),
    sa.Column('contact_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_activity_revision_details_entity_revision_id_entity_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_revision_id', name=op.f('pk_activity_revision_details'))
    )
    op.create_table('assessment_revision_details',
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=120), nullable=True),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timing_week', sa.Integer(), nullable=True),
    sa.Column('timing_text', sa.String(length=200), nullable=True),
    sa.Column('documented_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_hours_low', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_hours_typical', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_hours_high', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_assessment_revision_details_entity_revision_id_entity_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_revision_id', name=op.f('pk_assessment_revision_details'))
    )
    op.create_table('course_placements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('term', sa.Enum('fall', 'winter', 'spring', 'summer', 'full_year', 'unknown', name='term', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('pathway_id', sa.Uuid(), nullable=True),
    sa.Column('classification', sa.Enum('required', 'pathway_required', 'elective', 'optional', 'unknown', name='placementclass', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('offering_conditions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_course_placements_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_course_placements_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_course_placements_entity_revision_id_entity_revisions')),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], name=op.f('fk_course_placements_pathway_id_pathways')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_placements')),
    sa.UniqueConstraint('curriculum_version_id', 'entity_id', 'pathway_id', name=op.f('uq_course_placements_curriculum_version_id_entity_id_pathway_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_course_placements_curriculum_version_id'), 'course_placements', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_course_placements_entity_id'), 'course_placements', ['entity_id'], unique=False)
    op.create_table('course_revision_details',
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.Column('course_code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('credits', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_course_revision_details_entity_revision_id_entity_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_revision_id', name=op.f('pk_course_revision_details'))
    )
    op.create_index(op.f('ix_course_revision_details_course_code'), 'course_revision_details', ['course_code'], unique=False)
    op.create_table('curriculum_entity_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_curriculum_entity_memberships_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_curriculum_entity_memberships_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_curriculum_entity_memberships_entity_revision_id_entity_revisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_entity_memberships')),
    sa.UniqueConstraint('curriculum_version_id', 'entity_id', name=op.f('uq_curriculum_entity_memberships_curriculum_version_id_entity_id'))
    )
    op.create_index(op.f('ix_curriculum_entity_memberships_curriculum_version_id'), 'curriculum_entity_memberships', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_curriculum_entity_memberships_entity_id'), 'curriculum_entity_memberships', ['entity_id'], unique=False)
    op.create_index(op.f('ix_curriculum_entity_memberships_entity_revision_id'), 'curriculum_entity_memberships', ['entity_revision_id'], unique=False)
    op.create_table('curriculum_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('applicability', sa.Text(), nullable=True),
    sa.Column('authority', sa.Enum('authoritative', 'supporting', 'historical_reference', 'exploratory', name='sourceauthority', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('approval_status', sa.Enum('proposed', 'approved', 'rejected', name='approvalstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('is_exploratory_cross_version', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_curriculum_sources_assigned_by_users')),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_curriculum_sources_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_curriculum_sources_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_curriculum_sources_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_sources')),
    sa.UniqueConstraint('document_version_id', 'curriculum_version_id', name=op.f('uq_curriculum_sources_document_version_id_curriculum_version_id'))
    )
    op.create_index(op.f('ix_curriculum_sources_curriculum_version_id'), 'curriculum_sources', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_curriculum_sources_document_version_id'), 'curriculum_sources', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_curriculum_sources_organization_id'), 'curriculum_sources', ['organization_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_chunks_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_chunks_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index(op.f('ix_document_chunks_document_version_id'), 'document_chunks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_index('ix_document_chunks_tsv', 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('document_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=60), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('ocr_state', sa.Enum('not_needed', 'needed', 'done', 'unavailable', name='ocrstate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('char_boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', normalized_text)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_pages_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_version_id', 'page_number', name=op.f('uq_document_pages_document_version_id_page_number'))
    )
    op.create_index(op.f('ix_document_pages_document_version_id'), 'document_pages', ['document_version_id'], unique=False)
    op.create_index('ix_document_pages_tsv', 'document_pages', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('evidence_spans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_end > char_start', name=op.f('ck_evidence_spans_span_order')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_evidence_spans_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_spans_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_spans'))
    )
    op.create_index(op.f('ix_evidence_spans_document_version_id'), 'evidence_spans', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_evidence_spans_organization_id'), 'evidence_spans', ['organization_id'], unique=False)
    op.create_table('ingest_stage_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_ingest_stage_runs_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_stage_runs')),
    sa.UniqueConstraint('document_version_id', 'stage', 'parser_version', name=op.f('uq_ingest_stage_runs_document_version_id_stage_parser_version'))
    )
    op.create_index(op.f('ix_ingest_stage_runs_document_version_id'), 'ingest_stage_runs', ['document_version_id'], unique=False)
    op.create_table('outcome_revision_details',
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('statement_verbatim', sa.Text(), nullable=True),
    sa.Column('normalized_label', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_outcome_revision_details_entity_revision_id_entity_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_revision_id', name=op.f('pk_outcome_revision_details'))
    )
    op.create_table('requirement_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('elective_group', 'requirement', name='requirementgroupkind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('min_courses', sa.Integer(), nullable=True),
    sa.Column('min_credits', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('member_entity_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_requirement_groups_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_requirement_groups_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_groups')),
    sa.UniqueConstraint('curriculum_version_id', 'code', name=op.f('uq_requirement_groups_curriculum_version_id_code'))
    )
    op.create_index(op.f('ix_requirement_groups_curriculum_version_id'), 'requirement_groups', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_requirement_groups_organization_id'), 'requirement_groups', ['organization_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('base_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'under_review', 'approved', 'published', 'archived', name='scenariostate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('head', sa.Integer(), nullable=False),
    sa.Column('workload_assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['curriculum_versions.id'], name=op.f('fk_scenarios_base_version_id_curriculum_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scenarios_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_scenarios_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_base_version_id'), 'scenarios', ['base_version_id'], unique=False)
    op.create_index(op.f('ix_scenarios_organization_id'), 'scenarios', ['organization_id'], unique=False)
    op.create_table('topic_revision_details',
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('level', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_topic_revision_details_entity_revision_id_entity_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_revision_id', name=op.f('pk_topic_revision_details'))
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_revision', sa.Integer(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled', name='jobstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_analysis_runs_curriculum_version_id_curriculum_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analysis_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_analysis_runs_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index(op.f('ix_analysis_runs_curriculum_version_id'), 'analysis_runs', ['curriculum_version_id'], unique=False)
    op.create_index('ix_analysis_runs_hash', 'analysis_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_analysis_runs_organization_id'), 'analysis_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_scenario_id'), 'analysis_runs', ['scenario_id'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_chunk_embeddings_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_embeddings')),
    sa.UniqueConstraint('chunk_id', 'embedding_model', 'dimension', name=op.f('uq_chunk_embeddings_chunk_id_embedding_model_dimension'))
    )
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index('ix_chunk_embeddings_hnsw', 'chunk_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversations_created_by_users')),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_conversations_curriculum_version_id_curriculum_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_conversations_program_id_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_conversations_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_curriculum_version_id'), 'conversations', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversations_program_id'), 'conversations', ['program_id'], unique=False)
    op.create_table('entity_field_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_revision_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('evidence_span_id', sa.Uuid(), nullable=False),
    sa.Column('stance', sa.Enum('supporting', 'contradicting', name='evidencestance', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.ForeignKeyConstraint(['entity_revision_id'], ['entity_revisions.id'], name=op.f('fk_entity_field_evidence_entity_revision_id_entity_revisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_spans.id'], name=op.f('fk_entity_field_evidence_evidence_span_id_evidence_spans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_field_evidence')),
    sa.UniqueConstraint('entity_revision_id', 'field_name', 'evidence_span_id', name=op.f('uq_entity_field_evidence_entity_revision_id_field_name_evidence_span_id'))
    )
    op.create_index(op.f('ix_entity_field_evidence_entity_revision_id'), 'entity_field_evidence', ['entity_revision_id'], unique=False)
    op.create_index(op.f('ix_entity_field_evidence_evidence_span_id'), 'entity_field_evidence', ['evidence_span_id'], unique=False)
    op.create_table('requirement_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('rule_kind', sa.Enum('prerequisite', 'corequisite', 'antirequisite', name='rulekind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('origin', sa.Enum('extracted', 'manual', 'ai_inferred', 'rule_derived', 'synthetic_fixture', name='origin', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('evidence_basis', sa.Enum('explicit_statement', 'interpretation', 'assumption', name='evidencebasis', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('review_state', sa.Enum('proposed', 'accepted', 'rejected', 'superseded', name='reviewstate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('evidence_span_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_requirement_rules_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_spans.id'], name=op.f('fk_requirement_rules_evidence_span_id_evidence_spans')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_requirement_rules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_requirement_rules_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_rules'))
    )
    op.create_index(op.f('ix_requirement_rules_curriculum_version_id'), 'requirement_rules', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_requirement_rules_organization_id'), 'requirement_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requirement_rules_target_entity_id'), 'requirement_rules', ['target_entity_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('viewport', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_saved_views_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saved_views_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_saved_views_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_views_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views')),
    sa.UniqueConstraint('user_id', 'curriculum_version_id', 'name', name=op.f('uq_saved_views_user_id_curriculum_version_id_name'))
    )
    op.create_index(op.f('ix_saved_views_curriculum_version_id'), 'saved_views', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_saved_views_organization_id'), 'saved_views', ['organization_id'], unique=False)
    op.create_table('scenario_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('op_type', sa.String(length=60), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scenario_changes_created_by_users')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_changes_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_changes')),
    sa.UniqueConstraint('scenario_id', 'seq', name=op.f('uq_scenario_changes_scenario_id_seq'))
    )
    op.create_index(op.f('ix_scenario_changes_scenario_id'), 'scenario_changes', ['scenario_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', name='severity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('consequence_class', sa.Enum('direct_documented', 'indirect_potential', 'uncertain_inferred', 'judgment_needed', 'missing_evidence', name='consequenceclass', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('evidence_basis', sa.Enum('explicit_statement', 'interpretation', 'assumption', name='evidencebasis', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('affected_entity_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_findings_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_analysis_run_id'), 'findings', ['analysis_run_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('relationship_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_key', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('rel_type', sa.Enum('has_outcome', 'covers_topic', 'has_assessment', 'has_activity', 'contributes_to', 'assesses', 'supports', 'formal_prerequisite', 'corequisite', 'inferred_preparation', 'prepares_for', 'possible_overlap', name='reltype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('origin', sa.Enum('extracted', 'manual', 'ai_inferred', 'rule_derived', 'synthetic_fixture', name='origin', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('evidence_basis', sa.Enum('explicit_statement', 'interpretation', 'assumption', name='evidencebasis', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('review_state', sa.Enum('proposed', 'accepted', 'rejected', 'superseded', name='reviewstate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('contribution_level', sa.Enum('introduce', 'reinforce', 'assess', name='contributionlevel', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('requirement_rule_id', sa.Uuid(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_entity_id <> target_entity_id', name=op.f('ck_relationship_revisions_no_self_loop')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_relationship_revisions_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_relationship_revisions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_rule_id'], ['requirement_rules.id'], name=op.f('fk_relationship_revisions_requirement_rule_id_requirement_rules')),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_relationship_revisions_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_relationship_revisions_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_revisions')),
    sa.UniqueConstraint('relationship_key', 'revision_number', name=op.f('uq_relationship_revisions_relationship_key_revision_number'))
    )
    op.create_index('ix_rel_rev_source_type', 'relationship_revisions', ['source_entity_id', 'rel_type'], unique=False)
    op.create_index('ix_rel_rev_target_type', 'relationship_revisions', ['target_entity_id', 'rel_type'], unique=False)
    op.create_index(op.f('ix_relationship_revisions_organization_id'), 'relationship_revisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_relationship_revisions_relationship_key'), 'relationship_revisions', ['relationship_key'], unique=False)
    op.create_table('curriculum_relationship_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_key', sa.Uuid(), nullable=False),
    sa.Column('relationship_revision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_curriculum_relationship_memberships_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_revision_id'], ['relationship_revisions.id'], name=op.f('fk_curriculum_relationship_memberships_relationship_revision_id_relationship_revisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_relationship_memberships')),
    sa.UniqueConstraint('curriculum_version_id', 'relationship_key', name=op.f('uq_curriculum_relationship_memberships_curriculum_version_id_relationship_key'))
    )
    op.create_index(op.f('ix_curriculum_relationship_memberships_curriculum_version_id'), 'curriculum_relationship_memberships', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_curriculum_relationship_memberships_relationship_key'), 'curriculum_relationship_memberships', ['relationship_key'], unique=False)
    op.create_index(op.f('ix_curriculum_relationship_memberships_relationship_revision_id'), 'curriculum_relationship_memberships', ['relationship_revision_id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_span_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_revision_id', sa.Uuid(), nullable=True),
    sa.Column('requirement_rule_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_spans.id'], name=op.f('fk_finding_evidence_evidence_span_id_evidence_spans')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_evidence_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_revision_id'], ['relationship_revisions.id'], name=op.f('fk_finding_evidence_relationship_revision_id_relationship_revisions')),
    sa.ForeignKeyConstraint(['requirement_rule_id'], ['requirement_rules.id'], name=op.f('fk_finding_evidence_requirement_rule_id_requirement_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_evidence'))
    )
    op.create_index(op.f('ix_finding_evidence_finding_id'), 'finding_evidence', ['finding_id'], unique=False)
    op.create_table('finding_paths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_paths_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_paths'))
    )
    op.create_index(op.f('ix_finding_paths_finding_id'), 'finding_paths', ['finding_id'], unique=False)
    op.create_table('relationship_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('relationship_revision_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_span_id', sa.Uuid(), nullable=False),
    sa.Column('stance', sa.Enum('supporting', 'contradicting', name='evidencestance', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_spans.id'], name=op.f('fk_relationship_evidence_evidence_span_id_evidence_spans')),
    sa.ForeignKeyConstraint(['relationship_revision_id'], ['relationship_revisions.id'], name=op.f('fk_relationship_evidence_relationship_revision_id_relationship_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_evidence')),
    sa.UniqueConstraint('relationship_revision_id', 'evidence_span_id', name=op.f('uq_relationship_evidence_relationship_revision_id_evidence_span_id'))
    )
    op.create_index(op.f('ix_relationship_evidence_evidence_span_id'), 'relationship_evidence', ['evidence_span_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_relationship_revision_id'), 'relationship_evidence', ['relationship_revision_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('possible_duplicate', 'uncertain_course_match', 'candidate_entity', 'candidate_relationship', 'inferred_mapping', 'conflicting_requirement', 'missing_academic_year', 'unreadable_page', 'weak_evidence', name='reviewitemkind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'edited', 'rejected', 'deferred', name='reviewitemstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=True),
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_span_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=True),
    sa.Column('subject_relationship_revision_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_review_items_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_review_items_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_review_items_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], name=op.f('fk_review_items_subject_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_relationship_revision_id'], ['relationship_revisions.id'], name=op.f('fk_review_items_subject_relationship_revision_id_relationship_revisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_review_items_dedupe_key'))
    )
    op.create_index(op.f('ix_review_items_curriculum_version_id'), 'review_items', ['curriculum_version_id'], unique=False)
    op.create_index(op.f('ix_review_items_document_version_id'), 'review_items', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_review_items_organization_id'), 'review_items', ['organization_id'], unique=False)
    op.create_index('ix_review_items_status', 'review_items', ['organization_id', 'status'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_item_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('open', 'accepted', 'edited', 'rejected', 'deferred', name='reviewitemstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('edited_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_review_decisions_decided_by_users')),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], name=op.f('fk_review_decisions_review_item_id_review_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    op.create_index(op.f('ix_review_decisions_review_item_id'), 'review_decisions', ['review_item_id'], unique=False)

    # Immutable revisions: entity and relationship revisions are append-only.
    op.execute("""
    CREATE OR REPLACE FUNCTION cfs_forbid_update() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION '% rows are immutable; create a new revision instead', TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
    END; $$ LANGUAGE plpgsql;
    """)
    for t in ("entity_revisions", "relationship_revisions", "evidence_spans"):
        op.execute(f"CREATE TRIGGER {t}_immutable BEFORE UPDATE ON {t} FOR EACH ROW EXECUTE FUNCTION cfs_forbid_update()")

    # Published curriculum versions are immutable snapshots.
    op.execute("""
    CREATE OR REPLACE FUNCTION cfs_forbid_published_change() RETURNS trigger AS $$
    DECLARE v_status text;
    BEGIN
      SELECT status INTO v_status FROM curriculum_versions
       WHERE id = COALESCE(NEW.curriculum_version_id, OLD.curriculum_version_id);
      IF v_status = 'published' AND current_setting('cfs.publishing', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'curriculum version is published and immutable (%.%)', TG_TABLE_NAME, TG_OP
          USING ERRCODE = 'restrict_violation';
      END IF;
      RETURN COALESCE(NEW, OLD);
    END; $$ LANGUAGE plpgsql;
    """)
    for t in ("curriculum_entity_memberships", "curriculum_relationship_memberships", "course_placements",
              "requirement_rules", "requirement_groups"):
        op.execute(f"CREATE TRIGGER {t}_published_guard BEFORE INSERT OR UPDATE OR DELETE ON {t} "
                   f"FOR EACH ROW EXECUTE FUNCTION cfs_forbid_published_change()")
    # ### end Alembic commands ###


def downgrade() -> None:
    for t in ("curriculum_entity_memberships", "curriculum_relationship_memberships", "course_placements",
              "requirement_rules", "requirement_groups"):
        op.execute(f"DROP TRIGGER IF EXISTS {t}_published_guard ON {t}")
    for t in ("entity_revisions", "relationship_revisions", "evidence_spans"):
        op.execute(f"DROP TRIGGER IF EXISTS {t}_immutable ON {t}")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_decisions_review_item_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index('ix_review_items_status', table_name='review_items')
    op.drop_index(op.f('ix_review_items_organization_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_document_version_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_curriculum_version_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_relationship_evidence_relationship_revision_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_evidence_span_id'), table_name='relationship_evidence')
    op.drop_table('relationship_evidence')
    op.drop_index(op.f('ix_finding_paths_finding_id'), table_name='finding_paths')
    op.drop_table('finding_paths')
    op.drop_index(op.f('ix_finding_evidence_finding_id'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index(op.f('ix_curriculum_relationship_memberships_relationship_revision_id'), table_name='curriculum_relationship_memberships')
    op.drop_index(op.f('ix_curriculum_relationship_memberships_relationship_key'), table_name='curriculum_relationship_memberships')
    op.drop_index(op.f('ix_curriculum_relationship_memberships_curriculum_version_id'), table_name='curriculum_relationship_memberships')
    op.drop_table('curriculum_relationship_memberships')
    op.drop_index(op.f('ix_relationship_revisions_relationship_key'), table_name='relationship_revisions')
    op.drop_index(op.f('ix_relationship_revisions_organization_id'), table_name='relationship_revisions')
    op.drop_index('ix_rel_rev_target_type', table_name='relationship_revisions')
    op.drop_index('ix_rel_rev_source_type', table_name='relationship_revisions')
    op.drop_table('relationship_revisions')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_findings_analysis_run_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scenario_changes_scenario_id'), table_name='scenario_changes')
    op.drop_table('scenario_changes')
    op.drop_index(op.f('ix_saved_views_organization_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_curriculum_version_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_requirement_rules_target_entity_id'), table_name='requirement_rules')
    op.drop_index(op.f('ix_requirement_rules_organization_id'), table_name='requirement_rules')
    op.drop_index(op.f('ix_requirement_rules_curriculum_version_id'), table_name='requirement_rules')
    op.drop_table('requirement_rules')
    op.drop_index(op.f('ix_entity_field_evidence_evidence_span_id'), table_name='entity_field_evidence')
    op.drop_index(op.f('ix_entity_field_evidence_entity_revision_id'), table_name='entity_field_evidence')
    op.drop_table('entity_field_evidence')
    op.drop_index(op.f('ix_conversations_program_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_curriculum_version_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_chunk_embeddings_hnsw', table_name='chunk_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_analysis_runs_scenario_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_organization_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_hash', table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_curriculum_version_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('topic_revision_details')
    op.drop_index(op.f('ix_scenarios_organization_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_base_version_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_requirement_groups_organization_id'), table_name='requirement_groups')
    op.drop_index(op.f('ix_requirement_groups_curriculum_version_id'), table_name='requirement_groups')
    op.drop_table('requirement_groups')
    op.drop_table('outcome_revision_details')
    op.drop_index(op.f('ix_ingest_stage_runs_document_version_id'), table_name='ingest_stage_runs')
    op.drop_table('ingest_stage_runs')
    op.drop_index(op.f('ix_evidence_spans_organization_id'), table_name='evidence_spans')
    op.drop_index(op.f('ix_evidence_spans_document_version_id'), table_name='evidence_spans')
    op.drop_table('evidence_spans')
    op.drop_index('ix_document_pages_tsv', table_name='document_pages', postgresql_using='gin')
    op.drop_index(op.f('ix_document_pages_document_version_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index('ix_document_chunks_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_version_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_curriculum_sources_organization_id'), table_name='curriculum_sources')
    op.drop_index(op.f('ix_curriculum_sources_document_version_id'), table_name='curriculum_sources')
    op.drop_index(op.f('ix_curriculum_sources_curriculum_version_id'), table_name='curriculum_sources')
    op.drop_table('curriculum_sources')
    op.drop_index(op.f('ix_curriculum_entity_memberships_entity_revision_id'), table_name='curriculum_entity_memberships')
    op.drop_index(op.f('ix_curriculum_entity_memberships_entity_id'), table_name='curriculum_entity_memberships')
    op.drop_index(op.f('ix_curriculum_entity_memberships_curriculum_version_id'), table_name='curriculum_entity_memberships')
    op.drop_table('curriculum_entity_memberships')
    op.drop_index(op.f('ix_course_revision_details_course_code'), table_name='course_revision_details')
    op.drop_table('course_revision_details')
    op.drop_index(op.f('ix_course_placements_entity_id'), table_name='course_placements')
    op.drop_index(op.f('ix_course_placements_curriculum_version_id'), table_name='course_placements')
    op.drop_table('course_placements')
    op.drop_table('assessment_revision_details')
    op.drop_table('activity_revision_details')
    op.drop_index(op.f('ix_tool_calls_model_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_pathways_program_id'), table_name='pathways')
    op.drop_index(op.f('ix_pathways_organization_id'), table_name='pathways')
    op.drop_table('pathways')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_entity_revisions_organization_id'), table_name='entity_revisions')
    op.drop_index('ix_entity_revisions_fts', table_name='entity_revisions', postgresql_using='gin')
    op.drop_index(op.f('ix_entity_revisions_entity_id'), table_name='entity_revisions')
    op.drop_table('entity_revisions')
    op.drop_index(op.f('ix_document_versions_sha256'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_organization_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_curriculum_versions_program_id'), table_name='curriculum_versions')
    op.drop_index(op.f('ix_curriculum_versions_organization_id'), table_name='curriculum_versions')
    op.drop_table('curriculum_versions')
    op.drop_index(op.f('ix_programs_organization_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_model_runs_organization_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_cache_key'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_entities_organization_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS cfs_forbid_published_change()")
    op.execute("DROP FUNCTION IF EXISTS cfs_forbid_update()")
